language: java

jdk:
  - oraclejdk11

cache:
  directories:
  - "$HOME/.m2/repository"

env:  
  global:  
    - DISPLAY=:99.0

before_install:
   - sh -e /etc/init.d/xvfb start - sleep 10

install: true

script:
 - mvn -f releng/gef4/pom.xml clean verify -DuseUIThread=false -Dtycho.localArtifacts=ignore -Declipse.p2.mirrors=false -DskipTests